### ISSUE TITLE
MachineInventory object not created

### ISSUE THREAD

**Issue by kungfuchicken** [rancher-sandbox/rancher-node-image#10]
I've got an OS installed, and verified it has a hostname
I've got a MachineRegistration in Rancher cluster
I've got a Cluster in Rancher

Instructions at https://github.com/rancher-sandbox/rancher-node-image/blob/main/getting-started.md#add-nodes-to-cluster indicate that a MachineInventory object should exist in my Rancher cluster (2.6.5), but one was not automatically created.

What am I missing?

**Comment by kkaempf** [comment]
The MachineInventory object is created by `ros-installer` 
`ros-installer` runs when you boot the ISO as instructed in the getting started description.

**Comment by kkaempf** [comment]
.
